<?php

namespace T1Schema;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Generated translations for Schema.org presentation metadata.
 *
 * Do not edit this file directly. Run:
 * php bin/generate-schema-translations.php
 *
 * @package T1Schema
 */
class SchemaTypeTranslations {

    /**
     * Localize labels and descriptions without changing machine identifiers.
     *
     * @param array<string, array> $types Canonical schema definitions.
     * @return array<string, array> Localized definitions.
     */
    public static function localize( array $types ): array {
        $labels       = self::labels();
        $descriptions = self::descriptions();

        foreach ( $types as &$definition ) {
            if ( isset( $definition['label'], $labels[ $definition['label'] ] ) ) {
                $definition['label'] = $labels[ $definition['label'] ];
            }

            if ( isset( $definition['description'], $descriptions[ $definition['description'] ] ) ) {
                $definition['description'] = $descriptions[ $definition['description'] ];
            }

            foreach ( $definition['properties'] ?? [] as &$property ) {
                if ( isset( $property['description'], $descriptions[ $property['description'] ] ) ) {
                    $property['description'] = $descriptions[ $property['description'] ];
                }
            }
            unset( $property );
        }
        unset( $definition );

        return $types;
    }

    /** @return array<string, string> */
    private static function labels(): array {
        return [
            'Aggregate Offer' => _x( 'Aggregate Offer', 'Schema.org type label', 'teil1-schema-manager' ),
            'Aggregate Rating' => _x( 'Aggregate Rating', 'Schema.org type label', 'teil1-schema-manager' ),
            'Answer' => _x( 'Answer', 'Schema.org type label', 'teil1-schema-manager' ),
            'Article' => _x( 'Article', 'Schema.org type label', 'teil1-schema-manager' ),
            'Blog Posting' => _x( 'Blog Posting', 'Schema.org type label', 'teil1-schema-manager' ),
            'Breadcrumb List' => _x( 'Breadcrumb List', 'Schema.org type label', 'teil1-schema-manager' ),
            'Collection Page' => _x( 'Collection Page', 'Schema.org type label', 'teil1-schema-manager' ),
            'Course' => _x( 'Course', 'Schema.org type label', 'teil1-schema-manager' ),
            'Creative Work' => _x( 'Creative Work', 'Schema.org type label', 'teil1-schema-manager' ),
            'Defined Term' => _x( 'Defined Term', 'Schema.org type label', 'teil1-schema-manager' ),
            'Defined Term Set' => _x( 'Defined Term Set', 'Schema.org type label', 'teil1-schema-manager' ),
            'Event' => _x( 'Event', 'Schema.org type label', 'teil1-schema-manager' ),
            'FAQ Page' => _x( 'FAQ Page', 'Schema.org type label', 'teil1-schema-manager' ),
            'How-To' => _x( 'How-To', 'Schema.org type label', 'teil1-schema-manager' ),
            'How-To Step' => _x( 'How-To Step', 'Schema.org type label', 'teil1-schema-manager' ),
            'Image' => _x( 'Image', 'Schema.org type label', 'teil1-schema-manager' ),
            'Job Posting' => _x( 'Job Posting', 'Schema.org type label', 'teil1-schema-manager' ),
            'List Item' => _x( 'List Item', 'Schema.org type label', 'teil1-schema-manager' ),
            'Local Business' => _x( 'Local Business', 'Schema.org type label', 'teil1-schema-manager' ),
            'Offer' => _x( 'Offer', 'Schema.org type label', 'teil1-schema-manager' ),
            'Organization' => _x( 'Organization', 'Schema.org type label', 'teil1-schema-manager' ),
            'Person' => _x( 'Person', 'Schema.org type label', 'teil1-schema-manager' ),
            'Product' => _x( 'Product', 'Schema.org type label', 'teil1-schema-manager' ),
            'Professional Service' => _x( 'Professional Service', 'Schema.org type label', 'teil1-schema-manager' ),
            'Question' => _x( 'Question', 'Schema.org type label', 'teil1-schema-manager' ),
            'Recipe' => _x( 'Recipe', 'Schema.org type label', 'teil1-schema-manager' ),
            'Review' => _x( 'Review', 'Schema.org type label', 'teil1-schema-manager' ),
            'Service' => _x( 'Service', 'Schema.org type label', 'teil1-schema-manager' ),
            'Software Application' => _x( 'Software Application', 'Schema.org type label', 'teil1-schema-manager' ),
            'Technical Article' => _x( 'Technical Article', 'Schema.org type label', 'teil1-schema-manager' ),
            'Thing' => _x( 'Thing', 'Schema.org type label', 'teil1-schema-manager' ),
            'Video' => _x( 'Video', 'Schema.org type label', 'teil1-schema-manager' ),
            'Web Page' => _x( 'Web Page', 'Schema.org type label', 'teil1-schema-manager' ),
            'WebSite' => _x( 'WebSite', 'Schema.org type label', 'teil1-schema-manager' ),
        ];
    }

    /** @return array<string, string> */
    private static function descriptions(): array {
        return [
            'A blog post.' => _x( 'A blog post.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A breadcrumb trail for navigation.' => _x( 'A breadcrumb trail for navigation.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A code identifying this term within a term set.' => _x( 'A code identifying this term within a term set.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A job posting.' => _x( 'A job posting.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A page containing FAQ entries.' => _x( 'A page containing FAQ entries.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A page that lists or aggregates items, such as an archive or index page.' => _x( 'A page that lists or aggregates items, such as an archive or index page.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A person (alive, dead, undead, or fictional).' => _x( 'A person (alive, dead, undead, or fictional).', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A physical business with a local presence.' => _x( 'A physical business with a local presence.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A price range across multiple offers for the same item, e.g. a product with several variations.' => _x( 'A price range across multiple offers for the same item, e.g. a product with several variations.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A product offered for sale.' => _x( 'A product offered for sale.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A professional service business (agency, consultancy, law firm, etc.).' => _x( 'A professional service business (agency, consultancy, law firm, etc.).', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A question with an accepted answer.' => _x( 'A question with an accepted answer.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A recipe for cooking.' => _x( 'A recipe for cooking.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A review of an item.' => _x( 'A review of an item.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A service provided by an organization.' => _x( 'A service provided by an organization.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A set of defined terms — a glossary, taxonomy, or controlled vocabulary.' => _x( 'A set of defined terms — a glossary, taxonomy, or controlled vocabulary.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A short description.' => _x( 'A short description.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A single step in a how-to.' => _x( 'A single step in a how-to.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A single web page.' => _x( 'A single web page.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A software application.' => _x( 'A software application.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A technical article — how-to, reference, or documentation.' => _x( 'A technical article — how-to, reference, or documentation.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A video file or embed.' => _x( 'A video file or embed.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A website.' => _x( 'A website.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'A word, name, acronym, or phrase with a formal definition — ideal for glossary/lexicon entries.' => _x( 'A word, name, acronym, or phrase with a formal definition — ideal for glossary/lexicon entries.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'An answer to a question.' => _x( 'An answer to a question.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'An article, such as a news or blog article.' => _x( 'An article, such as a news or blog article.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'An educational course.' => _x( 'An educational course.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'An event happening at a certain time and location.' => _x( 'An event happening at a certain time and location.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'An image file.' => _x( 'An image file.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'An item in a list.' => _x( 'An item in a list.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'An offer to sell a product or service.' => _x( 'An offer to sell a product or service.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'An organization such as a company, NGO, club, etc.' => _x( 'An organization such as a company, NGO, club, etc.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'App category.' => _x( 'App category.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Application deadline.' => _x( 'Application deadline.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Application name.' => _x( 'Application name.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Array of Question items.' => _x( 'Array of Question items.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Article author.' => _x( 'Article author.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Article headline (max 110 chars).' => _x( 'Article headline (max 110 chars).', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Article image URL.' => _x( 'Article image URL.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Article summary.' => _x( 'Article summary.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Availability status URL.' => _x( 'Availability status URL.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Average rating from multiple sources.' => _x( 'Average rating from multiple sources.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Average rating.' => _x( 'Average rating.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Business description.' => _x( 'Business description.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Business logo.' => _x( 'Business logo.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Business name.' => _x( 'Business name.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Business website URL.' => _x( 'Business website URL.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Canonical references (e.g. Wikipedia, Wikidata URLs).' => _x( 'Canonical references (e.g. Wikipedia, Wikidata URLs).', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Contact email.' => _x( 'Contact email.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Contact phone number.' => _x( 'Contact phone number.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Cooking steps.' => _x( 'Cooking steps.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Cooking time.' => _x( 'Cooking time.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Course description.' => _x( 'Course description.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Course name.' => _x( 'Course name.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Course provider.' => _x( 'Course provider.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Creator.' => _x( 'Creator.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Currency code (e.g. EUR).' => _x( 'Currency code (e.g. EUR).', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Date founded.' => _x( 'Date founded.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Date posted.' => _x( 'Date posted.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Definition or explanation of the term.' => _x( 'Definition or explanation of the term.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Description of the glossary.' => _x( 'Description of the glossary.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Description.' => _x( 'Description.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Direct video file URL.' => _x( 'Direct video file URL.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Embed player URL.' => _x( 'Embed player URL.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'End date/time.' => _x( 'End date/time.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Event description.' => _x( 'Event description.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Event image.' => _x( 'Event image.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Event location.' => _x( 'Event location.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Event name.' => _x( 'Event name.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Full name.' => _x( 'Full name.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Geographic area served.' => _x( 'Geographic area served.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Geographic coordinates.' => _x( 'Geographic coordinates.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Highest possible rating.' => _x( 'Highest possible rating.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Highest price across all offers.' => _x( 'Highest price across all offers.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Hiring company.' => _x( 'Hiring company.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Image URL.' => _x( 'Image URL.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Image caption.' => _x( 'Image caption.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Image file URL.' => _x( 'Image file URL.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Image for the how-to.' => _x( 'Image for the how-to.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Image height in pixels.' => _x( 'Image height in pixels.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Image of the business.' => _x( 'Image of the business.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Image width in pixels.' => _x( 'Image width in pixels.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Instructions for a task.' => _x( 'Instructions for a task.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Item URL.' => _x( 'Item URL.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Item name.' => _x( 'Item name.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Job description.' => _x( 'Job description.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Job location.' => _x( 'Job location.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Job title.' => _x( 'Job title.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Last modified date.' => _x( 'Last modified date.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'List of ingredients.' => _x( 'List of ingredients.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Lowest possible rating.' => _x( 'Lowest possible rating.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Lowest price across all offers.' => _x( 'Lowest price across all offers.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Modified date.' => _x( 'Modified date.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Name of the item.' => _x( 'Name of the item.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Name of the term set (e.g. \'SEO Glossary\').' => _x( 'Name of the term set (e.g. \'SEO Glossary\').', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Number of distinct offers in the range.' => _x( 'Number of distinct offers in the range.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Number of reviews.' => _x( 'Number of reviews.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Number of servings.' => _x( 'Number of servings.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Opening hours.' => _x( 'Opening hours.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Ordered breadcrumb items.' => _x( 'Ordered breadcrumb items.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Page URL.' => _x( 'Page URL.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Page description.' => _x( 'Page description.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Page title.' => _x( 'Page title.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Page where image appears.' => _x( 'Page where image appears.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Personal website.' => _x( 'Personal website.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Phone number.' => _x( 'Phone number.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Photo URL.' => _x( 'Photo URL.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Physical address.' => _x( 'Physical address.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Position in the list.' => _x( 'Position in the list.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Post author.' => _x( 'Post author.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Post headline.' => _x( 'Post headline.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Post image.' => _x( 'Post image.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Preparation time.' => _x( 'Preparation time.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Prerequisites or dependencies.' => _x( 'Prerequisites or dependencies.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Price range (e.g. $$$).' => _x( 'Price range (e.g. $$$).', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Price value.' => _x( 'Price value.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Pricing and availability.' => _x( 'Pricing and availability.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Pricing information.' => _x( 'Pricing information.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Primary image.' => _x( 'Primary image.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Product brand.' => _x( 'Product brand.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Product description.' => _x( 'Product description.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Product image.' => _x( 'Product image.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Product name.' => _x( 'Product name.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Product review.' => _x( 'Product review.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Proficiency level (Beginner, Expert).' => _x( 'Proficiency level (Beginner, Expert).', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Publication date.' => _x( 'Publication date.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Publish date in ISO 8601.' => _x( 'Publish date in ISO 8601.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Publish date.' => _x( 'Publish date.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Publisher.' => _x( 'Publisher.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Publishing organization.' => _x( 'Publishing organization.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Rating given.' => _x( 'Rating given.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Recipe image.' => _x( 'Recipe image.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Recipe name.' => _x( 'Recipe name.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Review author.' => _x( 'Review author.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Review text.' => _x( 'Review text.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Salary information.' => _x( 'Salary information.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Search action for sitelinks search box.' => _x( 'Search action for sitelinks search box.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Service description.' => _x( 'Service description.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Service name.' => _x( 'Service name.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Service provider.' => _x( 'Service provider.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Social media profile URLs.' => _x( 'Social media profile URLs.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Social profile URLs.' => _x( 'Social profile URLs.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Start date/time.' => _x( 'Start date/time.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Step image.' => _x( 'Step image.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Step instructions.' => _x( 'Step instructions.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Step title.' => _x( 'Step title.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Steps to complete.' => _x( 'Steps to complete.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Stock keeping unit.' => _x( 'Stock keeping unit.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Supported OS.' => _x( 'Supported OS.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Terms in this set.' => _x( 'Terms in this set.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'The URL of the organization\'s website.' => _x( 'The URL of the organization\'s website.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'The accepted answer.' => _x( 'The accepted answer.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'The answer text.' => _x( 'The answer text.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'The glossary/taxonomy this term belongs to.' => _x( 'The glossary/taxonomy this term belongs to.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'The most generic kind of creative work.' => _x( 'The most generic kind of creative work.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'The most generic type. Every Schema.org type is a specialization of Thing.' => _x( 'The most generic type. Every Schema.org type is a specialization of Thing.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'The name of the organization.' => _x( 'The name of the organization.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'The question text.' => _x( 'The question text.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'The term being defined.' => _x( 'The term being defined.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Thumbnail image URL.' => _x( 'Thumbnail image URL.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Ticket information.' => _x( 'Ticket information.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Title of the how-to.' => _x( 'Title of the how-to.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Title of the work.' => _x( 'Title of the work.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Total time required.' => _x( 'Total time required.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Total time.' => _x( 'Total time.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Type of service.' => _x( 'Type of service.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'URL of the item.' => _x( 'URL of the item.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'URL of the organization logo.' => _x( 'URL of the organization logo.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'URL of the term set page.' => _x( 'URL of the term set page.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'URL of the term\'s page.' => _x( 'URL of the term\'s page.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'URL to purchase.' => _x( 'URL to purchase.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Upload date.' => _x( 'Upload date.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Video description.' => _x( 'Video description.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Video duration (ISO 8601).' => _x( 'Video duration (ISO 8601).', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Video title.' => _x( 'Video title.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Website URL.' => _x( 'Website URL.', 'Schema.org type or property description', 'teil1-schema-manager' ),
            'Website name.' => _x( 'Website name.', 'Schema.org type or property description', 'teil1-schema-manager' ),
        ];
    }
}
